# Based on: https://github.com/jdblischak/smk-simple-slurm
# Default slurm profile for running the pipeline on the eRI
executor: cluster-generic
cluster-generic-submit-cmd:
  mkdir -p logs/{rule} &&
  sbatch
    --account={resources.account}
    --partition={resources.partition}
    --cpus-per-task={threads}
    --mem="{resources.mem_gb}G"
    --time={resources.time}
    --job-name=smk-{rule}-{wildcards}
    --output=logs/{rule}/{rule}-{wildcards}-%j.out
    --parsable
cluster-generic-cancel-cmd: scancel
default-resources:
  - account=2023-mbie-rumen-gbs
  - partition=compute
  - time=30
  - mem_gb=8
restart-times: 3
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 2
latency-wait: 600
jobs: 100
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: greedy
use-conda: True
rerun-trigger: mtime
